# Generated by Django 6.0.1 on 2026-02-18 13:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_alter_orderitem_product_alter_product_collection_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="last_updates",
            new_name="last_update",
        ),
    ]
