# Generated by Django 6.0.1 on 2026-02-19 01:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_alter_customer_options_remove_customer_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"permissions": [("cancel_order", "can cancel order")]},
        ),
    ]
